# Generated by Django 4.2.1 on 2023-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
