# Generated by Django 4.2.1 on 2023-06-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0003_curso_persona_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
