# Generated by Django 4.2.2 on 2023-07-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_departamento_empleado_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Nocturno')], max_length=1, null=True)),
                ('h_extras', models.CharField(choices=[('S', 'Si trabajo'), ('N', 'No trabajo')], max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='jornada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.jornada'),
        ),
    ]
