# Generated by Django 4.2.2 on 2023-07-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_jornada_empleado_jornada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='h_extras',
        ),
    ]
